### ISSUE TITLE
[Exception] Incorrect use of ParentDataWidget.

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#107]
# PROB
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while looking for parent data.:
Incorrect use of ParentDataWidget.

The following ParentDataWidgets are providing parent data to the same RenderObject:
- Expanded(flex: 1) (typically placed directly inside a Flex widget)
- Expanded(flex: 1) (typically placed directly inside a Flex widget)
However, a RenderObject can only receive parent data from at most one ParentDataWidget.

Usually, this indicates that at least one of the offending ParentDataWidgets listed above is not placed directly inside a compatible ancestor widget.

The ownership chain for the RenderObject that received the parent data was:
  Center ← Obx ← Tickets ← Expanded ← Obx ← Expanded ← Column ← ColoredBox ← Container ← Listener ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._findAncestorParentDataElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:5715:11)
#1      RenderObjectElement._findAncestorParentDataElement (package:flutter/src/widgets/framework.dart:5729:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6080:62)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5751:5)
#4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6299:11)
...     Normal element mounting (23 frames)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#32     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#33     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#34     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#35     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#36     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#37     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#38     _invoke (dart:ui/hooks.dart:148:13)
#39     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#40     _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================
```
# SNaP
![Screenshot (545)](https://user-images.githubusercontent.com/24685590/206377336-694f519f-bf71-494f-ae5d-47a0f13d0cd7.png)

**Comment by sakibguy** [comment]
# Effort 1
> https://stackoverflow.com/questions/54905388/incorrect-use-of-parent-data-widget-expanded-widgets-must-be-placed-inside-flex

**Comment by sakibguy** [comment]
# Log (studio)

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(bg: Color(0xffffffff)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5260 pos 16: 'child is! ParentDataElement<ParentData>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Container Container:file:///D:/myalice_app/lib/screens/inboxScreen/inboxScreen.dart:469:20
When the exception was thrown, this was the stack: 
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5260:16)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5261:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#6      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5264:5)
#7      ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5308:5)
#8      ProxyElement.updated (package:flutter/src/widgets/framework.dart:5238:5)
#9      ProxyElement.update (package:flutter/src/widgets/framework.dart:5226:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#18     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#29     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#40     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#45     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#49     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#58     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#67     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#71     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#75     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#79     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#85     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#86     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#90     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#93     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#95     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#104    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#107    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#109    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#115    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#120    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#122    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#125    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#127    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#131    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#139    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#142    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#148    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#153    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#156    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#158    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#159    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#160    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#161    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#162    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#163    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
```

Then 
https://github.com/sakibguy/worked-issues/issues/107#issue-1483854587

**Comment by sakibguy** [comment]
# oSlved
> Auto solved where no major/minor changes on codebase. Just rollback/uncommented to past design and comment again to activate new design and issue auto solved. Live server was down, stage wasn't down (snap added below) but still not addressed reason & solution of the exception if raised again.

# SNaP
![1](https://user-images.githubusercontent.com/24685590/206401082-e2f1f4f1-73eb-4093-90eb-5e3bf54375dd.png)
