### ISSUE TITLE
SG-MYALICE: Unhandled Exception: DioError [DioErrorType.response]: Http status error [504]

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#109]
# PROB
```
E/flutter ( 1363): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.response]: Http status error [504]
E/flutter ( 1363): Source stack:
E/flutter ( 1363): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
E/flutter ( 1363): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
E/flutter ( 1363): #2      DioMixin.post (package:dio/src/dio_mixin.dart:97:12)
E/flutter ( 1363): #3      ChatApiController.sendConvChats (package:myalice/controllers/apiControllers/chatApiController.dart:509:10)
E/flutter ( 1363): #4      ChatTextingController.sendConvText (package:myalice/controllers/viewController/chatTextingViewController.dart:186:12)
E/flutter ( 1363): #5      ChatTextingController.sendConvChat (package:myalice/controllers/viewController/chatTextingViewController.dart:141:5)
E/flutter ( 1363): #6      _ChatMsgSendDraggableView.build.<anonymous closure>.<anonymous closure> (package:myalice/screens/chatDetails/customWidgets/chatBottomViews/chatMsgSendDraggableView.dart:401:64)
E/flutter ( 1363): #7      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
E/flutter ( 1363): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
E/flutter ( 1363): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
E/flutter ( 1363): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
E/flutter ( 1363): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239:7)
E/flutter ( 1363): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615:9)
E/flutter ( 1363): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
E/flutter ( 1363): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
E/flutter ( 1363): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
E/flutter ( 1363): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
E/flutter ( 1363): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
E/flutter ( 1363): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
E/flutter ( 1363): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
E/flutter ( 1363): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
E/flutter ( 1363): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
E/flutter ( 1363): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
E/flutter ( 1363): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
E/flutter ( 1363): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 1363): #25     _invoke1 (dart:ui/hooks.dart:167:13)
E/flutter ( 1363): #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
E/flutter ( 1363): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
E/flutter ( 1363): 
E/flutter ( 1363): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:643:7)
E/flutter ( 1363): #1      _RootZone.runBinary (dart:async/zone.dart:1658:54)
E/flutter ( 1363): #2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter ( 1363): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter ( 1363): #4      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter ( 1363): #5      Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 1363): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
E/flutter ( 1363): #7      _Completer.completeError (dart:async/future_impl.dart:23:5)
E/flutter ( 1363): #8      Future.any.onError (dart:async/future.dart:617:45)
E/flutter ( 1363): #9      _RootZone.runBinary (dart:async/zone.dart:1658:54)
E/flutter ( 1363): #10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter ( 1363): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter ( 1363): #12     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter ( 1363): #13     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 1363): #14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
E/flutter ( 1363): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 1363): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 1363):
```

# SNaP
![Screenshot (602)](https://user-images.githubusercontent.com/24685590/207843068-2e9aeb55-6673-4c5b-86f9-d5c203af76ed.png)

**Comment by sakibguy** [comment]
Ignore now as working on dev_branch without any issues https://github.com/sakibguy/worked-issues/issues/111#issuecomment-1356781365
