### ISSUE TITLE
SG-MYALICE: Button gallery block exception by pusher on UI

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#115]
# PROB
> Button Gallery: get-conversation (showing button gallery) but pusher/realtime getting exception.

# SNaP
![Screenshot (639)](https://user-images.githubusercontent.com/24685590/208404027-c9ee09cf-1e8e-4d98-aaac-d7c6e3d94a4d.png)

# EXCEP
> exception 1

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building ConversationBaseWidget(dirty, state: _ConversationBaseWidget#753bc):
Null check operator used on a null value

The relevant error-causing widget was: 
  ConversationBaseWidget ConversationBaseWidget:file:///D:/myalice_app/lib/screens/chatDetails/chatDetails.dart:371:43
When the exception was thrown, this was the stack: 
#0      _ConversationBaseWidget.getBorderBarHeight (package:myalice/screens/chatDetails/customWidgets/conversationWidgets/conversationBaseWidget.dart:195:45)
#1      _ConversationBaseWidget.build (package:myalice/screens/chatDetails/customWidgets/conversationWidgets/conversationBaseWidget.dart:437:53)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (41 frames)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#54     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1405:37)
#55     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1306:35)
#56     Iterable.forEach (dart:core/iterable.dart:325:35)
#57     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1353:24)
#58     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1282:7)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
```

> exception 2

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:107:12)
#3      _ConvBtnQuickReplyWidget.initState.<anonymous closure> (package:myalice/screens/chatDetails/customWidgets/conversationWidgets/conversationBtnQuickReplyWidget.dart:48:52)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#7      _invoke (dart:ui/hooks.dart:148:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#9      _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by sakibguy** [comment]
# Pusher resp

`{"type": "message", "source": "bot", "platform_type": "facebook_messenger", "platform_id": 1361, "customer_id": 1043, "project_id": 375, "conversation_id": "m_45EF2QmBrO4_krkp30HFOk6MoMJwaz_uVqGmpI3rBU9zznxcJN5lbyn1MaJzZAbiOY5rcKItdTHTgaDm9j6p9w", "success": true, "report": {"recipient_id": "4533558773428509", "message_id": "m_45EF2QmBrO4_krkp30HFOk6MoMJwaz_uVqGmpI3rBU9zznxcJN5lbyn1MaJzZAbiOY5rcKItdTHTgaDm9j6p9w"}, "timestamp": 1671446031085, "data": {"type": "quick_reply", "data": {"text": "Take a tour on our site..", "title": null, "save": false, "attribute": null, "buttons": [{"id": 1, "type": "sequence", "extra": "", "title": "Button Gallery", "value": 5500, "payload": "SEQ5500-1644133268903", "verbose": "imu - Gallery", "input_value": ""}, {"id": 2, "type": "sequence", "extra": "", "title": "Button Image", "value": 7723, "payload": "SEQ7723-1670503776191", "verbose": "image block", "input_value": ""}, {"id": 3, "type": "sequence", "extra": "", "title": "Button", "value": 7724, "payload": "SEQ7724-1670503828924", "verbose": "button block", "input_value": ""}], "api": null}}, "dataV2": {}}`

# SNaP
![Screenshot (641)](https://user-images.githubusercontent.com/24685590/208411389-502afb4c-0e29-4f86-ada7-54077aaf6071.png)

**Comment by sakibguy** [comment]
# SOLn
> Update data model by ElementButton 

```
class ElementButtons {
  int? id;
  String? type;
  String? extra;
  String? title;
  String? value;
  String? payload;
  String? verbose;
  int? formSequence;
  //Null formSequenceTitle;
  bool? messengerExtensions;
  String? webviewHeightRatio;

  ElementButtons(
      {this.id,
        this.type,
        this.extra,
        this.title,
        this.value,
        this.payload,
        this.verbose,
        this.formSequence,
        // this.formSequenceTitle,
        this.messengerExtensions,
        this.webviewHeightRatio});

  ElementButtons.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    type = json['type'];
    extra = json['extra'];
    title = json['title'];
    value = json['value'].toString();
    payload = json['payload'];
    verbose = json['verbose'];
    formSequence = json['form_sequence'];
    // formSequenceTitle = json['form_sequence_title'];
    messengerExtensions = json['messenger_extensions'];
    webviewHeightRatio = json['webview_height_ratio'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['type'] = this.type;
    data['extra'] = this.extra;
    data['title'] = this.title;
    data['value'] = this.value;
    data['payload'] = this.payload;
    data['verbose'] = this.verbose;
    data['form_sequence'] = this.formSequence;
    // data['form_sequence_title'] = this.formSequenceTitle;
    data['messenger_extensions'] = this.messengerExtensions;
    data['webview_height_ratio'] = this.webviewHeightRatio;
    return data;
  }
}
```

**Comment by sakibguy** [comment]
# REASON 
> REALTIME COMPATIBALITY/PARSING ISSUE (DATA vs DATAV2)

# SNaP
![1](https://user-images.githubusercontent.com/24685590/208466422-5133e425-5203-4a11-aff0-c6ad8be5781b.png)

**Comment by sakibguy** [comment]
# **Parse succeeded**
> pusher_bot: 

`{type: null, success: null, error: null, text: Button block test Button block test Button block test Button block test Button block test Button block test Button block test Button block test Button block test, payload: null, sub_type: null, urls: null, buttons: [{id: 1, type: sequence, extra: , title: Button Title 1, value: 7723, payload: SEQ7723-1670503776191, verbose: image block}, {id: 2, type: sequence, extra: , title: Button Title 2, value: 7723, payload: SEQ7723-1670503776191, verbose: image block}, {id: 3, type: sequence, extra: , title: Button Title 3, value: 7723, payload: SEQ7723-1670503776191, verbose: image block}]}`

**Comment by sakibguy** [comment]
# data vs dataV2 not compatible
> if make compatible complexity be raised on UI + pusher for chatlist updates be required extra codes. Not impossible! But not good practices!

# USHER: data(raise complexity) or dataV2(bot resp not ready)
![Screenshot (646)](https://user-images.githubusercontent.com/24685590/208597717-8f12f679-5dc1-4c10-99b4-f27740fe67d0.png)

![Screenshot (647)](https://user-images.githubusercontent.com/24685590/208597783-53976c4c-5c11-4e71-b627-7bc8f2fc1096.png)

![Screenshot (648)](https://user-images.githubusercontent.com/24685590/208597859-24331dae-d785-4d55-a4d8-d840cd3bb5d6.png)

**Comment by sakibguy** [comment]
# SOLn
> Nargis Apu, got a solution and I would know from new changes https://github.com/sakibguy/worked-issues/issues/108#issuecomment-1366468998

> So, **closed the issue.**
