### ISSUE TITLE
RU-MAKEAPP:  java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#116]
# PROB
> rebuilt: https://github.com/sakibguy/ru_makeapp-rebuild-footballtransfer
> project: https://github.com/sakibguy/ru_makeapp-DailyFootballTransfer

```
E/FlutterLoader(11502): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader(11502):         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(11502):         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(11502):         at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/FlutterLoader(11502):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader(11502):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader(11502):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/FlutterLoader(11502):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/FlutterLoader(11502):         at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader(11502):         at android.app.Activity.performCreate(Activity.java:8051)
E/FlutterLoader(11502):         at android.app.Activity.performCreate(Activity.java:8031)
E/FlutterLoader(11502):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/FlutterLoader(11502):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
E/FlutterLoader(11502):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
E/FlutterLoader(11502):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/FlutterLoader(11502):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FlutterLoader(11502):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FlutterLoader(11502):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/FlutterLoader(11502):         at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader(11502):         at android.os.Looper.loopOnce(Looper.java:201)
E/FlutterLoader(11502):         at android.os.Looper.loop(Looper.java:288)
E/FlutterLoader(11502):         at android.app.ActivityThread.main(ActivityThread.java:7839)
E/FlutterLoader(11502):         at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(11502):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/FlutterLoader(11502):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/FlutterLoader(11502): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader(11502):         at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/FlutterLoader(11502):         at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/FlutterLoader(11502):         at java.lang.System.loadLibrary(System.java:1656)
E/FlutterLoader(11502):         at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader(11502):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/FlutterLoader(11502):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/FlutterLoader(11502):         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader(11502):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader(11502):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader(11502):         at java.lang.Thread.run(Thread.java:920)
E/AndroidRuntime(11502): FATAL EXCEPTION: main
E/AndroidRuntime(11502): Process: com.da1lyfo0tball.transfer, PID: 11502
E/AndroidRuntime(11502): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.da1lyfo0tball.transfer/com.da1lyfo0tball.transfer.daily_football_transfer.MainActivity}:
 java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(11502):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
E/AndroidRuntime(11502):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
E/AndroidRuntime(11502):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(11502):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(11502):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(11502):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/AndroidRuntime(11502):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11502):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(11502):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(11502):        at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(11502):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11502):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(11502):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(11502): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not foun
d
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:345)
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/AndroidRuntime(11502):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/AndroidRuntime(11502):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(11502):        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(11502):        at android.app.Activity.performCreate(Activity.java:8051)
E/AndroidRuntime(11502):        at android.app.Activity.performCreate(Activity.java:8031)
E/AndroidRuntime(11502):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime(11502):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
E/AndroidRuntime(11502):        ... 12 more
E/AndroidRuntime(11502): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(11502):        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/AndroidRuntime(11502):        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/AndroidRuntime(11502):        ... 21 more
E/AndroidRuntime(11502): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(11502):        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime(11502):        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(11502):        at java.lang.System.loadLibrary(System.java:1656)
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/AndroidRuntime(11502):        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/AndroidRuntime(11502):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(11502):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(11502):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(11502):        at java.lang.Thread.run(Thread.java:920)
```

# SNaP
![Screenshot (653)](https://user-images.githubusercontent.com/24685590/209179652-6dd7e913-6a9b-4d7e-9dd6-03b40ed0881e.png)

**Comment by sakibguy** [comment]
# Efforts
1- https://github.com/flutter/flutter/issues/108079
2- https://stackoverflow.com/questions/66363437/flutter-release-bundle-or-apk-crash-on-start-dlopen-failed-library-libflutter?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+stackoverflow%2FOxiZ+%28%5Bandroid+questions%5D%29
