### ISSUE TITLE
SG-MYALICE: Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#125]
# PROB

```
I/flutter (11462): ERROR[null] => PATH: https://stage-api.myalice.ai/api/accounts/info
E/flutter (11462): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (11462): #0      LoggingInterceptors.onError (package:myalice/controllers/apiControllers/interceptor.dart:61:23)
E/flutter (11462): #1      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
E/flutter (11462): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
E/flutter (11462): #3      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
E/flutter (11462): #4      new Future.<anonymous closure> (dart:async/future.dart:253:37)
E/flutter (11462): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (11462): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (11462): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (11462): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (11462): 
```

# SNaP

![Screenshot (726)](https://user-images.githubusercontent.com/24685590/212562192-5686c629-f22c-426e-8388-e7e42af57bd6.png)

**Comment by sakibguy** [comment]
# App locked to go next page
![Screenshot (727)](https://user-images.githubusercontent.com/24685590/212562363-fbfb765f-2352-473c-8c9f-0290a71e6808.png)

![1](https://user-images.githubusercontent.com/24685590/212562414-f4efba3c-a3f6-4e14-91c9-911162de8c4a.png)

**Comment by sakibguy** [comment]
# Conflicts 
> git checkout revamp_features

> git pull origin revamp_features

## SNaP
![Screenshot (728)](https://user-images.githubusercontent.com/24685590/212562775-bcc74837-0728-41c7-87ce-565b2d037aeb.png)

**Comment by sakibguy** [comment]
# SOLn
![1](https://user-images.githubusercontent.com/24685590/212602138-acc272c1-df63-4d32-bfae-88971ad7b791.png)

**Comment by sakibguy** [comment]
# PROB
> Merge conflict: **sakib_revamp_features vs revamp_features**

# SNaP
![1](https://user-images.githubusercontent.com/24685590/212604028-a737dbee-1f25-41ad-b2ae-eb1a83a583cf.png)

**Comment by sakibguy** [comment]
# SOLn
![1](https://user-images.githubusercontent.com/24685590/212605508-34fa9156-a1dc-417b-8437-7ebb54c54091.png)

**Comment by sakibguy** [comment]
# SAME PROB 3
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value

```
I/flutter (18359): ERROR[null] => PATH: https://stage-api.myalice.ai/api/accounts/login
E/flutter (18359): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (18359): #0      LoginApiController.login (package:myalice/controllers/apiControllers/loginApiController.dart:21:51)
E/flutter (18359): <asynchronous suspension>
E/flutter (18359): 
I/flutter (18359): ERROR[null] => PATH: https://stage-api.myalice.ai/api/accounts/login
E/flutter (18359): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (18359): #0      LoginApiController.login (package:myalice/controllers/apiControllers/loginApiController.dart:21:51)
E/flutter (18359): <asynchronous suspension>
E/flutter (18359): 
```

## SNaP
![1](https://user-images.githubusercontent.com/24685590/213868353-7be60bb9-4523-414a-a2eb-6e5d765e8a17.png)
![2](https://user-images.githubusercontent.com/24685590/213868360-2600e367-3065-41d5-baea-04d4215cafef.png)
![3](https://user-images.githubusercontent.com/24685590/213868364-3dade261-a2b4-465b-a112-52fbb1242a80.png)

**Comment by sakibguy** [comment]
# SOLn
> Auto solved, might be server issued. 

## SNaP
![1](https://user-images.githubusercontent.com/24685590/213903792-9604f204-4bd6-4285-a2eb-0cf6e32c1152.png)

**Comment by sakibguy** [comment]
# IMPACT  
> PR https://github.com/alice-labs/myalice_app/pull/74

**Comment by sakibguy** [comment]
https://github.com/alice-labs/myalice_app/pull/78
