### ISSUE TITLE
SG-MYALICE: Invalid argument(s): No host specified in URI

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#126]
# PROB

```
======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2591:7)
#2      IOClient.send (package:http/src/io_client.dart:57:38)
#3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:35:44)
#4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:121:24)
#5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:103:28)
<asynchronous suspension>
#6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:71:7)
<asynchronous suspension>
Image provider: CachedNetworkImageProvider("", scale: 1.0) 
 Image key: CachedNetworkImageProvider("", scale: 1.0): CachedNetworkImageProvider("", scale: 1.0)
====================================================================================================
```

## SNaP
![1](https://user-images.githubusercontent.com/24685590/214025951-05fe8242-2044-4339-b4d3-6e5f4e9ceecb.png)

**Comment by sakibguy** [comment]
# IMPACT  
> PR https://github.com/alice-labs/myalice_app/pull/74

**Comment by sakibguy** [comment]
https://github.com/alice-labs/myalice_app/pull/78
