### ISSUE TITLE
SG-MYALICE: Login failed

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#130]
# PROB 1
> Suddenly login failed. Tried many times but couldn't. 

# SNaP
![1](https://user-images.githubusercontent.com/24685590/216820892-b7657b17-1db5-4ca2-9f7c-e8ce8f9f1475.png)

**Comment by sakibguy** [comment]
# NO ISSUE VERIFIED 
![1](https://user-images.githubusercontent.com/24685590/216821260-30728e1a-5b88-4723-b5d3-40c9a429e2a1.png)

**Comment by sakibguy** [comment]
# TESTED WEB/STAGE
> masuma+1@myalice.ai logged in

## SNaP
![1](https://user-images.githubusercontent.com/24685590/216821515-f1f3b379-2b7e-4223-8763-f685299d7869.png)

**Comment by sakibguy** [comment]
# ERROR 
```
I/flutter (15447): ERROR[null] => PATH: https://stage-api.myalice.ai/api/accounts/login
E/flutter (15447): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (15447): #0      LoginApiController.login (package:myalice/controllers/apiControllers/loginApiController.dart:21:51)
E/flutter (15447): <asynchronous suspension>
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/216821775-b17b1ac0-79f2-4dd8-887f-90f1dc404080.png)

**Comment by sakibguy** [comment]
# AUTO SOLVED 
![1](https://user-images.githubusercontent.com/24685590/216822742-a6c18ae5-e01e-4019-bca0-f664d3dd8052.png)

**Comment by sakibguy** [comment]
# new: PROB 2
```
I/flutter (15747): Data: null
I/flutter (15747): ERROR[null] => PATH: https://stage-api.myalice.ai/api/accounts/info
I/flutter (15747): Error!!!!! : DioError [DioErrorType.connectTimeout]: Connecting timed out [30000ms]
I/flutter (15747): Source stack:
I/flutter (15747): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (15747): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (15747): #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
I/flutter (15747): #3      SplashController.getUser (package:myalice/controllers/apiControllers/splashController.dart:13:12)
I/flutter (15747): #4      _SplashScreenState.whichScreenToNavigate.<anonymous closure> (package:myalice/screens/splashScreen.dart:36:35)
I/flutter (15747): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter (15747): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter (15747): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter (15747): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/216830648-b1eea2f3-ad05-49ce-9dfa-d78bea65713e.png)

**Comment by sakibguy** [comment]
# new: PROB 3
```
E/flutter (15747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#416b6(physicalKey: PhysicalKeyboardKey#7002a(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#00008(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:00:21.052863, synthesized)
E/flutter (15747): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (15747): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (15747): #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
E/flutter (15747): #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
E/flutter (15747): #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
E/flutter (15747): #5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:808:29)
E/flutter (15747): #6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:41)
E/flutter (15747): #7      _invoke1 (dart:ui/hooks.dart:167:13)
E/flutter (15747): #8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:408:7)
E/flutter (15747): #9      _invoke2 (dart:ui/hooks.dart:186:13)
E/flutter (15747): #10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (15747): #11     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (15747): #12     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (15747): #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
E/flutter (15747): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
E/flutter (15747):
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/216831988-78025dd6-4a11-4870-9404-1a91b374633d.png)

**Comment by sakibguy** [comment]
# AUTO SOLVED 
> Was server issue

## SNaP
![1](https://user-images.githubusercontent.com/24685590/216838979-d6b59a1c-7b19-4fc2-b7da-cc0eb7f337bc.png)

**Comment by sakibguy** [comment]
# new: PROB 4
### Agent, Group: `Null data`

```
E/flutter (15747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (15747): #0      _FilterPage.initAgentsGroups.<anonymous closure> (package:myalice/revamp/filter/view/filterPage.dart:507:49)
E/flutter (15747): #1      _RootZone.run (dart:async/zone.dart:1647:54)
E/flutter (15747): #2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:190:18)
E/flutter (15747): #3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:736:39)
E/flutter (15747): #4      Future._propagateToListeners (dart:async/future_impl.dart:792:11)
E/flutter (15747): #5      Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (15747): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
E/flutter (15747): #7      _Completer.completeError (dart:async/future_impl.dart:23:5)
E/flutter (15747): #8      Future.any.onError (dart:async/future.dart:617:45)
E/flutter (15747): #9      _RootZone.runBinary (dart:async/zone.dart:1658:54)
E/flutter (15747): #10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (15747): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter (15747): #12     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter (15747): #13     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (15747): #14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
E/flutter (15747): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (15747): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (15747): 
```

### Tags: `Null data`

```
E/flutter (15747): 
E/flutter (15747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (15747): #0      _FilterPage.initTags.<anonymous closure> (package:myalice/revamp/filter/view/filterPage.dart:577:12)
E/flutter (15747): #1      _RootZone.run (dart:async/zone.dart:1647:54)
E/flutter (15747): #2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:190:18)
E/flutter (15747): #3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:736:39)
E/flutter (15747): #4      Future._propagateToListeners (dart:async/future_impl.dart:792:11)
E/flutter (15747): #5      Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (15747): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
E/flutter (15747): #7      _Completer.completeError (dart:async/future_impl.dart:23:5)
E/flutter (15747): #8      Future.any.onError (dart:async/future.dart:617:45)
E/flutter (15747): #9      _RootZone.runBinary (dart:async/zone.dart:1658:54)
E/flutter (15747): #10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (15747): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter (15747): #12     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter (15747): #13     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (15747): #14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
E/flutter (15747): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (15747): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (15747):
``` 

# SNaP
![1](https://user-images.githubusercontent.com/24685590/216841462-5b6cee1d-07db-4823-b9ef-88d5a4a9eb9f.png)
![1](https://user-images.githubusercontent.com/24685590/216841603-2ae9139b-e4b2-4d15-8cff-f4d99e3c4943.png)

**Comment by sakibguy** [comment]
# SOLn
![1](https://user-images.githubusercontent.com/24685590/216887845-8e048b17-b63b-4271-9601-6feb418af8f0.png)

**Comment by sakibguy** [comment]
# IMPACT  
> PR https://github.com/alice-labs/myalice_app/pull/74

**Comment by sakibguy** [comment]
# new: PROB 5
### https://github.com/sakibguy/worked-issues/issues/131#issuecomment-1442264622

**Comment by sakibguy** [comment]
https://github.com/alice-labs/myalice_app/pull/78

**Comment by sakibguy** [comment]
# new: PROB 6
> https://github.com/sakibguy/worked-issues/issues/131#issuecomment-1454980173
