### ISSUE TITLE
SG-MYALICE: [UNSOLVED (4) SOLVED2] Web Bugs

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#131]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB1**(req)

# `SITUATION`: [UNSOLVED] `ALICEWEB_BUG_1`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** Not showing total num of tickets when updated private view filter fields, on top bar

> **SOLN:** Please

# `ACTION`: SNaP
## Showing

![1](https://user-images.githubusercontent.com/24685590/218957804-20e8e131-abe8-4c5c-b109-69e47e45d713.png)

### `Not showing`

![2](https://user-images.githubusercontent.com/24685590/218958023-6f8abeea-a623-4ed1-b982-5dc9428030bf.png)

# REPORTED 
![1](https://user-images.githubusercontent.com/24685590/218965482-5c4e6e53-2f50-48b2-8c3f-a93606a68df1.png)

# `RESULT`: NO

**Comment by sakibguy** [comment]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB2**(req)

# `SITUATION`: [UNSOLVED] `ALICEWEB_BUG_2`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** Private View: Which one consider as correct list for mobile? 

> **SOLN:** Please

# `ACTION`: SNaP
### Once showing A

![2](https://user-images.githubusercontent.com/24685590/219370576-6f112e0f-7ead-498a-8a79-b5b1dccf4126.png)

### Once showing B
![3](https://user-images.githubusercontent.com/24685590/219370589-c6cc1381-32a1-4bb1-be64-64b22d90c199.png)

# `RESULT`: NO

**Comment by sakibguy** [comment]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB3**(req)

# `SITUATION`: [UNSOLVED] `ALICEWEB_BUG_3`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** Private view: When delete filter, **Cancel button click event not working**. 1st I thought my laptop being freeze later understood cancel not functional.

> **SOLN:** Please

# `ACTION`: SNaP
![1](https://user-images.githubusercontent.com/24685590/219376251-3ca64da5-7f49-47de-b3c5-8b46d4a9d8e0.png)

# `RESULT`: NO

**Comment by sakibguy** [comment]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB4**(req)

# `SITUATION`: [SOLVED] `ALICEWEB_BUG_4`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** **`web vs mobile:` Showing diff channels sequence, leading filter result diff.** During filter, mobile channel s list vs web channel s list sequence not same. Mobile end getting **extra `LC p 2` channel** where web end not. And, this diff creating wrong filter result. At web showing 27 tickets filtered for 5 selected channels, at mobile showing 26 tickets filtered **for same 5 selected channels**. NOT SURE `LC p 2`, INJECTED NOISE DATA?

> **SOLN:** Please?

# `ACTION`: SNaP
![1](https://user-images.githubusercontent.com/24685590/219384015-b0c08f1a-b954-4e51-ac42-61fc73c59f33.png)
![2](https://user-images.githubusercontent.com/24685590/219382547-ea48cf59-cca3-417b-9157-2e256ab2506f.png)
![3](https://user-images.githubusercontent.com/24685590/219382550-2c944738-9b43-4452-8a26-fdddaa75172b.png)
![4](https://user-images.githubusercontent.com/24685590/219382558-467f0db3-e6ae-474e-a0b2-5bf83073ae58.png)
![5](https://user-images.githubusercontent.com/24685590/219382562-e1cca650-761e-417f-8928-455d5fa7c2b9.png)

# `RESULT`: YES

**Comment by sakibguy** [comment]
> 

# `AUTO SOLVED` 
> Mobile vs Web channels sequence not same but when selected same 5 channels then same 27 results both end. Thank a lot  for quick fixes.

# SNaP
![1](https://user-images.githubusercontent.com/24685590/219399888-72d039f8-0e5f-4dca-92a1-ad9f2ca87e22.png)
![2](https://user-images.githubusercontent.com/24685590/219399923-120c5434-9ea9-463d-8412-ef3bc2d02e1a.png)
![3](https://user-images.githubusercontent.com/24685590/219399928-0d83cd65-885b-4760-a36a-d9977ffd0c7a.png)
![4](https://user-images.githubusercontent.com/24685590/219399936-cbd294e4-0181-4d5d-bdb1-6c2fca34bc27.png)

**Comment by sakibguy** [comment]
> [**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB4**(req)
> 
> # [UNSOLVED] `ALICEWEB_BUG_4`
> > cc: @kmehran1106 bro @snrahman01 apu
> 
> > **PROB:** **`web vs mobile:` Showing diff channels sequence, leading filter result diff.** During filter, mobile channel s list vs web channel s list sequence not same. Mobile end getting **extra `LC p 2` channel** where web end not. And, this diff creating wrong filter result. At web showing 27 tickets filtered for 5 selected channels, at mobile showing 26 tickets filtered **for same 5 selected channels**. NOT SURE `LC p 2`, INJECTED NOISE DATA?
> 
> > **SOLN:** Please?
> 
> # SNaP
> ![1](https://user-images.githubusercontent.com/24685590/219384015-b0c08f1a-b954-4e51-ac42-61fc73c59f33.png) ![2](https://user-images.githubusercontent.com/24685590/219382547-ea48cf59-cca3-417b-9157-2e256ab2506f.png) ![3](https://user-images.githubusercontent.com/24685590/219382550-2c944738-9b43-4452-8a26-fdddaa75172b.png) ![4](https://user-images.githubusercontent.com/24685590/219382558-467f0db3-e6ae-474e-a0b2-5bf83073ae58.png) ![5](https://user-images.githubusercontent.com/24685590/219382562-e1cca650-761e-417f-8928-455d5fa7c2b9.png)

# `AUTO SOLVED` 
> Mobile vs Web channels sequence not same but when selected same 5 channels then same 27 results both end. Thank a lot  for quick fixes.

# SNaP
![1](https://user-images.githubusercontent.com/24685590/219399888-72d039f8-0e5f-4dca-92a1-ad9f2ca87e22.png)
![2](https://user-images.githubusercontent.com/24685590/219399923-120c5434-9ea9-463d-8412-ef3bc2d02e1a.png)
![3](https://user-images.githubusercontent.com/24685590/219399928-0d83cd65-885b-4760-a36a-d9977ffd0c7a.png)
![4](https://user-images.githubusercontent.com/24685590/219399936-cbd294e4-0181-4d5d-bdb1-6c2fca34bc27.png)

**Comment by sakibguy** [comment]
# CONNECTED  
> PR https://github.com/alice-labs/myalice_app/pull/74

**Comment by sakibguy** [comment]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB5**(req)

# `SITUATION`: [SOLVED] `ALICEWEB_BUG_5`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** Login failed. `Unhandled Exception: Null check operator used on a null value`. Internet ok, checked. Stage true. Passphrase ok. `But login failed.`

> **RELATED:** https://github.com/sakibguy/worked-issues/issues/130#issuecomment-1442266105

> **-ve IMPACT:** 
1. Delaying filter completion, to fail deadline
2. Recording poor performance 
3. No result to Alice
4. Time wasting 
5. ...etc

> **SOLN:** Please

```
I/flutter (12994): ERROR[null] => PATH: https://stage-api.myalice.ai/api/accounts/login
E/flutter (12994): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (12994): #0      LoginApiController.login (package:myalice/controllers/apiControllers/loginApiController.dart:21:51)
E/flutter (12994): <asynchronous suspension>
```

# `ACTION`: SNaP
![1](https://user-images.githubusercontent.com/24685590/221000586-e1b74c93-a053-4ea7-a2be-a834cb024395.png)
![2](https://user-images.githubusercontent.com/24685590/221000595-812d981a-1d5c-4fa4-b710-4ff00f8abeb2.png)

# SOLVED once
> As reported mobile-app channel within 30min solved. 

![2](https://user-images.githubusercontent.com/24685590/221017541-2cadd97e-19e1-4c20-809c-a33bcbfbaf62.png)

![1](https://user-images.githubusercontent.com/24685590/221017356-884873d2-b777-4949-a94e-feda99f791ba.png)

# `AUTO SOLVED WITHOUT PULLING REMOTE` 
> RECORDED: **Backend created issue.**

![1](https://user-images.githubusercontent.com/24685590/221018918-725ff867-2871-4dec-82de-9e0b1b778d7c.png)

# `AGAIN STOPPED LOGIN` 
> As Nargis apu said, Might be work only after pulling remote revamp_features branch or could be solved automatically again. I wait...to see. **But question is how auto solved few min ago without pulling (recorded above)?** 

![1](https://user-images.githubusercontent.com/24685590/221021122-742fceff-5449-4e7a-886e-ac2b133847be.png)

# `AUTO FIXED/LOGIN AGAIN`
> Without pulling revamp_feature auto logged in. Time recorded. 

![1](https://user-images.githubusercontent.com/24685590/221022287-bcc0d1b6-68d2-43e4-b1b0-8136f1309e66.png)

# `AGAIN STOPPED LOGIN`
> Waiting for new yying story... Ah 1hr time wasted.

![1](https://user-images.githubusercontent.com/24685590/221024916-9b1c60b2-1d0f-4932-a0c7-1186d3835cd7.png)

# `AUTO FIXED/LOGIN AGAIN`
> **Good Morning!** Without pulling revamp_feature auto logged in. **Time recorded.** 

![1](https://user-images.githubusercontent.com/24685590/221395002-7bfa1f7c-a786-4b5e-bd46-db1e67638c88.png)

# `RESULT`: YES

**Comment by sakibguy** [comment]
https://github.com/alice-labs/myalice_app/pull/78

**Comment by sakibguy** [comment]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB6**(req)

# `SITUATION`: [SOLVED] `ALICEWEB_BUG_6`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** Login failed. `Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'`

> **RELATED:** https://github.com/sakibguy/worked-issues/issues/131#issuecomment-1442264622

> **SOLN:** Please

```
I/flutter (12918): ERROR[504] => PATH: https://stage-api.myalice.ai/api/accounts/login
E/flutter (12918): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'
E/flutter (12918): #0      LoginApiController.login (package:myalice/controllers/apiControllers/loginApiController.dart:21:57)
E/flutter (12918): <asynchronous suspension>
```
# `ACTION`: SNaP
![1](https://user-images.githubusercontent.com/24685590/222940368-edf42a9b-40f3-4c08-b091-6f5fbe2fbc5b.png)

# `AUTO SOLVED`
> Internet was ok, checked. Stage true. Passphrase ok. But login failed. And, after few min later no issued.

![1](https://user-images.githubusercontent.com/24685590/222940514-3a2276a3-5f79-4243-8781-27327916b1a5.png)
# `RESULT`: YES

**Comment by sakibguy** [comment]
[**MSB8040**](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8040?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8040)%26rd%3Dtrue&view=vs-2022) (motiv) vs **ALICEWEBB7**(req)

# `SITUATION`: [UNSOLVED] `ALICEWEB_BUG_7`
> cc: @kmehran1106 bro @snrahman01 apu

> **PROB:** `Why getting data /noise data on mobile for agents & channels?` Project `hello` (3 noise data), project `asd` (2 noise data). As getting noise data empty state of agent not showing then masuma apu report it empty state bug. Where empty state completed tested perfectly on diff projects for agents, groups, tags. Web & mobile showing projects (hello & asd) have no  ticket lists but getting noise data during filter of agent, channel.

> **RELATED:** 

> **SOLN:** Please

```
I/flutter (12918): ERROR[504] => PATH: https://stage-api.myalice.ai/api/accounts/login
E/flutter (12918): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'
E/flutter (12918): #0      LoginApiController.login (package:myalice/controllers/apiControllers/loginApiController.dart:21:57)
E/flutter (12918): <asynchronous suspension>
```
# `ACTION`: SNaP
![1](https://user-images.githubusercontent.com/24685590/223370255-d0084cf5-9508-49f5-882d-10ebd14e77d0.png)
![2](https://user-images.githubusercontent.com/24685590/223370270-fe7ecdf5-efec-47cb-98ee-bdfbdfb518a0.png)
![3](https://user-images.githubusercontent.com/24685590/223370276-007efe87-5b23-472d-bf32-d52b45a78655.png)
![4](https://user-images.githubusercontent.com/24685590/223370284-ffe0260a-fd45-4f4f-8c36-01775e070dc8.png)


## **As getting noise data empty state not showing below**


![5](https://user-images.githubusercontent.com/24685590/223372191-6efe4092-b711-4c15-af3a-09242e16671b.png)
![6](https://user-images.githubusercontent.com/24685590/223372199-2751999c-8e8f-4606-b55b-657763cc9cd3.png)


# `RESULT`: NO
