### ISSUE TITLE
[org] RU-MAKEAPP: [Top Football] java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#136]
# PROB
> After merging nayan branch with main branch, pulled remote and locally getting build err.

```
Flutter initialization failed.
E/FlutterLoader(15731): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader(15731): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(15731): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/FlutterLoader(15731): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader(15731): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader(15731): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/FlutterLoader(15731): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/FlutterLoader(15731): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader(15731): 	at android.app.Activity.performCreate(Activity.java:8051)
E/FlutterLoader(15731): 	at android.app.Activity.performCreate(Activity.java:8031)
E/FlutterLoader(15731): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/FlutterLoader(15731): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
E/FlutterLoader(15731): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
E/FlutterLoader(15731): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/FlutterLoader(15731): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FlutterLoader(15731): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FlutterLoader(15731): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/FlutterLoader(15731): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader(15731): 	at android.os.Looper.loopOnce(Looper.java:201)
E/FlutterLoader(15731): 	at android.os.Looper.loop(Looper.java:288)
E/FlutterLoader(15731): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/FlutterLoader(15731): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(15731): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/FlutterLoader(15731): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/FlutterLoader(15731): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader(15731): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/FlutterLoader(15731): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/FlutterLoader(15731): 	at java.lang.System.loadLibrary(System.java:1656)
E/FlutterLoader(15731): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/FlutterLoader(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/FlutterLoader(15731): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader(15731): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader(15731): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader(15731): 	at java.lang.Thread.run(Thread.java:920)
E/AndroidRuntime(15731): FATAL EXCEPTION: main
E/AndroidRuntime(15731): Process: com.topf00tball.acdc, PID: 15731
E/AndroidRuntime(15731): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.topf00tball.acdc/com.example.topfootball.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(15731): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
E/AndroidRuntime(15731): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
E/AndroidRuntime(15731): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(15731): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15731): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15731): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/AndroidRuntime(15731): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15731): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(15731): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(15731): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(15731): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15731): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(15731): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(15731): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:345)
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/AndroidRuntime(15731): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/AndroidRuntime(15731): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(15731): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(15731): 	at android.app.Activity.performCreate(Activity.java:8051)
E/AndroidRuntime(15731): 	at android.app.Activity.performCreate(Activity.java:8031)
E/AndroidRuntime(15731): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime(15731): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
E/AndroidRuntime(15731): 	... 12 more
E/AndroidRuntime(15731): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(15731): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/AndroidRuntime(15731): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/AndroidRuntime(15731): 	... 21 more
E/AndroidRuntime(15731): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(15731): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime(15731): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(15731): 	at java.lang.System.loadLibrary(System.java:1656)
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/AndroidRuntime(15731): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/AndroidRuntime(15731): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(15731): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(15731): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(15731): 	at java.lang.Thread.run(Thread.java:920)
```

# SNaP

![1](https://user-images.githubusercontent.com/24685590/228588813-c65de510-8b26-4100-b77d-34804f77d3f4.png)
![2](https://user-images.githubusercontent.com/24685590/228588838-e5c120d0-8a33-48e5-900d-4a6dce84d1c5.png)
![3](https://user-images.githubusercontent.com/24685590/228588848-8a4ab196-7096-4690-8911-0f3f8dacd7ef.png)
![4](https://user-images.githubusercontent.com/24685590/228588869-638e5348-d979-4bfc-a6c4-6c3fd4ba7800.png)

**Comment by sakibguy** [comment]
# Effort 1: `FAILED` 
> https://stackoverflow.com/questions/65386544/flutter-initialization-failed-java-lang-unsatisfiedlinkerror-dlopen-failed-li

# SNaP
![1](https://user-images.githubusercontent.com/24685590/228606628-5232a71d-b453-4c88-8413-fd5f940fa517.png)

**Comment by sakibguy** [comment]
# Effort 2
> https://github.com/flutter/flutter/issues/73943

**Comment by sakibguy** [comment]
# DETECTED ISSUE REASON & `Rejected delivery`
> Fixed issues from sakib branch without anything integration from nayan branch. Built successfully apk & aab, those passed on https://keychecker.hardcody.ru/ too, below snaps added. So, from nayan branch build err reason was libflutter.so removed from src code, app ui not fixed perfectly as figma ui, player info desc not fixed perfectly as figma (no code changes found on nayan branch) .

> So, wasted time and unsafe team collaboration bhv for libflutter.so rejected delivery. 

> Future Java & flutter coding practices be strongly evaluated before accepted delivery or be rejected if anything unsafe detected.

## SNaP
> from sakib branch no issue on arch

![1](https://user-images.githubusercontent.com/24685590/228626809-8f651062-a2a8-42d0-b656-7717b348f0c0.png)
![2](https://user-images.githubusercontent.com/24685590/228626848-4b73866f-18d3-4d04-888e-569820157408.png)
![3](https://user-images.githubusercontent.com/24685590/228626862-5e460e56-d149-46b3-b71d-afa335be9a27.png)
![4](https://user-images.githubusercontent.com/24685590/228626868-4a2a3c65-935c-4024-9754-5d2abd4a715f.png)
