### ISSUE TITLE
[org] RU-MAKEAPP: [Latto Spin] Resolving Android Dependencies...

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#137]
# PROB
> Issue raised from Unity version: 2021.3.3f1 after changing pkg name, app name, diff options clicking not changing. Resolving Android Dependencies not finished. 

## LOGs

```
Running Gradle...

C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=D:/softwares/unity/install-all/2021.3.3f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Assets\Plugins\Android" "-PMAVEN_REPOS=https://artifact.bytedance.com/repository/pangle" "-PPACKAGES_TO_COPY=com.applovin:applovin-sdk:11.3.3;com.google.android.exoplayer:exoplayer:2.13.3;com.applovin.mediation:bytedance-adapter:4.9.0.8.0;com.applovin.mediation:facebook-adapter:[6.12.0.0]" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"
Executing command: C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=D:/softwares/unity/install-all/2021.3.3f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Assets\Plugins\Android" "-PMAVEN_REPOS=https://artifact.bytedance.com/repository/pangle" "-PPACKAGES_TO_COPY=com.applovin:applovin-sdk:11.3.3;com.google.android.exoplayer:exoplayer:2.13.3;com.applovin.mediation:bytedance-adapter:4.9.0.8.0;com.applovin.mediation:facebook-adapter:[6.12.0.0]" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"

ERROR: Gradle failed to fetch dependencies.

Failed to run 'C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=D:/softwares/unity/install-all/2021.3.3f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=C:\dev\code\ru_makeapp-rebuild-5unitygames\LattoLattoTrendingGame (2) (1)\LattoLattoTrendingGame (1)\Assets\Plugins\Android" "-PMAVEN_REPOS=https://artifact.bytedance.com/repository/pangle" "-PPACKAGES_TO_COPY=com.applovin:applovin-sdk:11.3.3;com.google.android.exoplayer:exoplayer:2.13.3;com.applovin.mediation:bytedance-adapter:4.9.0.8.0;com.applovin.mediation:facebook-adapter:[6.12.0.0]" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"'
stdout:
Downloading https://services.gradle.org/distributions/gradle-5.1.1-bin.zip
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

stderr:
Exception in thread "main" javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: Tag mismatch!
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1541)
	at sun.security.ssl.AppInputStream.available(AppInputStream.java:60)
	at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
	at sun.net.www.MeteredStream.available(MeteredStream.java:170)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3409)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:77)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: javax.net.ssl.SSLException: Tag mismatch!
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1020)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3329)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:62)
	... 7 more
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:524)
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1023)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:960)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
	at javax.crypto.Cipher.doFinal(Cipher.java:2377)
	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1015)
	... 16 more

exit code: 1
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/230136494-8a1b2a48-022a-423a-9d9b-9b9f44c36323.PNG)

**Comment by sakibguy** [comment]
# SOLn
> Closed window and updating config as gp ready.

**Comment by sakibguy** [comment]
# PROB 2
> After selected all 4 architectures, auto pop up window `Resolving Android Dependencies...` with above exception.  

# SNaP
![1](https://user-images.githubusercontent.com/24685590/230141549-7496580c-21fd-4678-9a81-73c6e3297f94.PNG)
![2](https://user-images.githubusercontent.com/24685590/230141561-1716fc34-c40d-45f4-b923-76281369f5ab.PNG)

![1](https://user-images.githubusercontent.com/24685590/230142044-d26bacdc-4f75-4421-8336-09e4d242de2c.PNG)

# BUILD TAKING HUGE TIME (16 MIN+)
![1](https://user-images.githubusercontent.com/24685590/230146495-23ebd304-f22d-46ec-ac16-6accb370511c.PNG)

# BUILD TAKING HUGE TIME (30 MIN+)
![32](https://user-images.githubusercontent.com/24685590/230151091-d5c5b86c-65b7-492d-86f4-da27b8844814.PNG)

**Comment by sakibguy** [comment]
# BUILD FAILED 
![1](https://user-images.githubusercontent.com/24685590/230151528-404a374e-0c2a-42fd-aef0-9614bd23c4a6.PNG)

# LOG

```
Resolution failed

Failed to fetch the following dependencies:
com.applovin:applovin-sdk:11.3.3
com.google.android.exoplayer:exoplayer:2.13.3
com.applovin.mediation:bytedance-adapter:4.9.0.8.0
com.applovin.mediation:facebook-adapter:[6.12.0.0]


UnityEngine.Debug:LogError (object)
Google.Logger:Log (string,Google.LogLevel) (at Z:/tmp/tmp.meXp0pQNTJ/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:136)
GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel) (at Z:/tmp/tmp.LTohvuzcD4/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1055)
GooglePlayServices.GradleResolver:LogMissingDependenciesError (System.Collections.Generic.List`1<string>) (at Z:/tmp/tmp.LTohvuzcD4/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:95)
GooglePlayServices.GradleResolver/<DoResolutionUnsafe>c__AnonStorey8:<>m__1 (System.Collections.Generic.List`1<Google.JarResolver.Dependency>) (at Z:/tmp/tmp.LTohvuzcD4/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:920)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1:<>m__0 () (at Z:/tmp/tmp.LTohvuzcD4/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:383)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1:<>m__2 (GooglePlayServices.CommandLine/Result) (at Z:/tmp/tmp.LTohvuzcD4/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:462)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1/<GradleResolution>c__AnonStorey3:<>m__0 () (at Z:/tmp/tmp.LTohvuzcD4/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:572)
Google.RunOnMainThread:ExecuteNext () (at Z:/tmp/tmp.meXp0pQNTJ/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1 () (at Z:/tmp/tmp.meXp0pQNTJ/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction (System.Action) (at Z:/tmp/tmp.meXp0pQNTJ/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested (bool) (at Z:/tmp/tmp.meXp0pQNTJ/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll () (at Z:/tmp/tmp.meXp0pQNTJ/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**Comment by sakibguy** [comment]
# Hold by TT
![1](https://user-images.githubusercontent.com/24685590/230328010-f0233054-c028-4602-9190-cc5cba788e53.PNG)
