### ISSUE TITLE
[org] RU-MAKEAPP: [ZigZag] UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#138]
# PROB
```
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bf] in <7105be432fb64891b07085914e6cd5c1>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <7105be432fb64891b07085914e6cd5c1>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/230282505-7967a824-7922-481d-9c44-39ee2c0a0e04.PNG)

**Comment by sakibguy** [comment]
# R+D: Effort 
1- https://stackoverflow.com/questions/71793462/build-error-unityeditor-buildplayerwindowbuildmethodexception-2-errors
2- https://answers.unity.com/questions/1453735/unityeditorbuildplayerwindowbuildmethodexception-2.html
3- Find past successful unity delivery settings and config same as past on new delivery.

**Comment by sakibguy** [comment]
# R+D: SOLn
> 1- https://github.com/sakibguy/ru_makeapp-clicktrick/releases

> 2- copy paste click trick build config https://gist.github.com/sakibguy/e71d4b198e15c293b6cd675066fdbb02

# SNaP
> Click trick showing same err too...

![1](https://user-images.githubusercontent.com/24685590/230303609-6b26f91d-1ec8-4e53-a5d8-0d0569a8c004.PNG)

# BUILD SUCCESSFUL 
> New APK built successfully

![2](https://user-images.githubusercontent.com/24685590/230304679-ec05de68-638b-4741-8afe-73562840a092.PNG)

**Comment by sakibguy** [comment]
# 1- BUILDING ZigZag 
![1](https://user-images.githubusercontent.com/24685590/230306703-006346db-9a8c-4a93-b0ff-7544680349e5.PNG)

# 2- BUILD FAILED: `LOG 1` 

```
Exception: D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\il2cpp/build/deploy/net471/il2cpp.exe did not run properly!

Failed running "D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\il2cpp/build/deploy/net471/il2cpp.exe" --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="C:\dev\code\ru_makeapp-rebuild-5unitygames\ZigZag\Zigzag (1)\Zigzag\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="C:\dev\code\ru_makeapp-rebuild-5unitygames\ZigZag\Zigzag (1)\Zigzag\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="D:/softwares/unity/install-all/2019.4.40f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="D:/softwares/unity/install-all/2019.4.40f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="D:/softwares/unity/install-all/2019.4.40f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser=D:/softwares/unity/install-all/2019.4.40f1/Editor/Data/Tools/MapFileParser/MapFileParser.exe --directory="C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Temp/StagingArea/assets/bin/Data/Managed" --generatedcppdir="C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Temp/StagingArea/Il2Cpp/il2cppOutput"  

stdout:
Building libil2cpp.so with AndroidToolChain
	Output directory: C:\dev\code\ru_makeapp-rebuild-5unitygames\ZigZag\Zigzag (1)\Zigzag\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a
	Cache directory: C:\dev\code\ru_makeapp-rebuild-5unitygames\ZigZag\Zigzag (1)\Zigzag\Library\il2cpp_android_armeabi-v7a\il2cpp_cache
ObjectFiles: 129 of which compiled: 0
Total compilation time: 152 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\User\AppData\Local\Temp\tmp78F5.tmp" -o "C:\dev\code\ru_makeapp-rebuild-5unitygames\ZigZag\Zigzag (1)\Zigzag\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_C648877ADDBC2C5187FFF26B02EE8EA2\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target armv7-linux-androideabi19 -Wl,--wrap,sigaction -llog -rdynamic -fuse-ld=gold.exe

D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/9E42BADC3337383E9D86C00DBBD3C6FC.o: section name section has wrong type: 0
D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/9E42BADC3337383E9D86C00DBBD3C6FC.o: bad section name offset for section 1: 0
D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/A819C57D34062FBE0E0B1E257D9FFAB0.o: section name section has wrong type: 2621440
D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: fatal error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/A819C57D34062FBE0E0B1E257D9FFAB0.o: attempt to map 3800936456 bytes at offset 3912058928 exceeds size of file; the file may be corrupt
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\User\AppData\Local\Temp\tmp78F5.tmp" -o "C:\dev\code\ru_makeapp-rebuild-5unitygames\ZigZag\Zigzag (1)\Zigzag\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_C648877ADDBC2C5187FFF26B02EE8EA2\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target armv7-linux-androideabi19 -Wl,--wrap,sigaction -llog -rdynamic -fuse-ld=gold.exe

D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/9E42BADC3337383E9D86C00DBBD3C6FC.o: section name section has wrong type: 0
D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/9E42BADC3337383E9D86C00DBBD3C6FC.o: bad section name offset for section 1: 0
D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/A819C57D34062FBE0E0B1E257D9FFAB0.o: section name section has wrong type: 2621440
D:\softwares\unity\install-all\2019.4.40f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld.gold.exe: fatal error: C:/dev/code/ru_makeapp-rebuild-5unitygames/ZigZag/Zigzag (1)/Zigzag/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/A819C57D34062FBE0E0B1E257D9FFAB0.o: attempt to map 3800936456 bytes at offset 3912058928 exceeds size of file; the file may be corrupt
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
   at il2cpp.Program.Main(String[] args)

UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <dd2e71f8d45046b88d6d3169a8084aec>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <dd2e71f8d45046b88d6d3169a8084aec>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <dd2e71f8d45046b88d6d3169a8084aec>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <dd2e71f8d45046b88d6d3169a8084aec>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <7105be432fb64891b07085914e6cd5c1>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

# 2- BUILD FAILED: `LOG 2`

```
Build completed with a result of 'Failed' in 36 seconds (36216 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

# 2- BUILD FAILED: `LOG 3`

```
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bf] in <7105be432fb64891b07085914e6cd5c1>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <7105be432fb64891b07085914e6cd5c1>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

**Comment by sakibguy** [comment]
# R+D
> 1- https://stackoverflow.com/questions/68712639/exception-il2cpp-exe-did-not-run-properly

# SNaP
![1](https://user-images.githubusercontent.com/24685590/230327409-5cb7add3-7214-43e5-b96f-91b95318f49d.PNG)

**Comment by sakibguy** [comment]
# Hold by TT
![1](https://user-images.githubusercontent.com/24685590/230328010-f0233054-c028-4602-9190-cc5cba788e53.PNG)
