### ISSUE TITLE
[org] RU-MAKEAPP: [Super Athletic] Caused by: java.lang.UnsupportedOperationException: addView(View, LayoutParams) is not supported in AdapterView 

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#139]
# PROB
> Caused by: java.lang.UnsupportedOperationException: addView(View, LayoutParams) is not supported in AdapterView

```
Process: com.supper.athler1c, PID: 15860
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.supper.athler1c/com.supper.athler1c.MainActivity}: android.view.InflateException: Binary XML file line #269 in com.supper.athler1c:layout/activity_main: addView(View, LayoutParams) is not supported in AdapterView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.view.InflateException: Binary XML file line #269 in com.supper.athler1c:layout/activity_main: addView(View, LayoutParams) is not supported in AdapterView
     Caused by: java.lang.UnsupportedOperationException: addView(View, LayoutParams) is not supported in AdapterView
        at android.widget.AdapterView.addView(AdapterView.java:515)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
        at com.supper.athler1c.MainActivity.onCreate(MainActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2023-04-22 22:39:00.192 15860-15870/com.supper.athler1c W/System: A resource failed to call close.
``` 

# SNaP
![1](https://user-images.githubusercontent.com/24685590/233796473-223e513f-ec19-4686-91e7-7b7ce7537b70.PNG)

**Comment by sakibguy** [comment]
# Addressed Issue 
> ListView inside ListView

![1](https://user-images.githubusercontent.com/24685590/233820031-9a90dbfb-04c3-440e-8cbe-e4433f4402d0.PNG)

**Comment by sakibguy** [comment]
# FIXED

![1](https://user-images.githubusercontent.com/24685590/233820129-d23c7031-84d4-49ac-99b7-2695bed567ff.PNG)
