### ISSUE TITLE
[org] RU-MAKEAPP: [Super Athletic] java.io.IOException: Failed to load asset path /data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#140]
# PROB
> Football: table data showing UI. Basketball: table data not showing UI.

```
2023-04-24 14:41:50.059 510-666/? E/WifiScoringParams: Invalid frequency(-1), using 5G as default rssi array
2023-04-24 14:41:55.812 731-731/? E/ndroid.systemu: Failed to open APK '/data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk': I/O error
2023-04-24 14:41:55.819 731-731/? E/ndroid.systemu: Failed to open APK '/data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk': I/O error
2023-04-24 14:41:55.821 731-731/? E/ResourcesManager: failed to add asset path '/data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk'
    java.io.IOException: Failed to load asset path /data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk
        at android.content.res.ApkAssets.nativeLoad(Native Method)
        at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
        at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
        at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
        at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
        at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
        at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:530)
        at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:612)
        at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:664)
        at android.app.ResourcesManager.createResources(ResourcesManager.java:1011)
        at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
        at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2372)
        at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
        at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
        at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
        at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3029)
        at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
        at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
        at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
        at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
        at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
        at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
        at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
        at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
        at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
        at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:140)
        at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1431)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2023-04-24 14:43:23.416 360-360/? E/android.hardware.power.stats@1.0-service-mock: Failed to getEnergyData
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/233945945-882ca48f-1c40-4f71-9fb6-4b5c7eb74705.PNG)
![2](https://user-images.githubusercontent.com/24685590/233946195-eec13414-9e03-4dcb-9b32-6490d601e590.PNG)
![3](https://user-images.githubusercontent.com/24685590/233946202-1831658c-26da-4c86-bb98-475f2500a0b9.PNG)

**Comment by sakibguy** [comment]
# Result
> Showing Basketball table data.
> Tackled null data.

![1](https://user-images.githubusercontent.com/24685590/233947324-7921d9c6-2fbc-414e-86db-f56307ee4b2a.PNG)
