### ISSUE TITLE
[org] RU-MAKEAPP: [Super Athletic] java.lang.RuntimeException: ManagedChannel allocation site

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#141]
# PROB
> Raised when clicked faster many network called events.

```
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at ejqh.<init>(:com.google.android.gms@231312047@23.13.12 (190800-519946965):3)
        at ejqi.<init>(:com.google.android.gms@231312047@23.13.12 (190800-519946965):2)
        at ejqg.a(:com.google.android.gms@231312047@23.13.12 (190800-519946965):21)
        at ejid.a(:com.google.android.gms@231312047@23.13.12 (190800-519946965):0)
        at abck.H(:com.google.android.gms@231312047@23.13.12 (190800-519946965):22)
        at abck.f(:com.google.android.gms@231312047@23.13.12 (190800-519946965):2)
        at aoje.a(:com.google.android.gms@231312047@23.13.12 (190800-519946965):75)
        at abbs.call(:com.google.android.gms@231312047@23.13.12 (190800-519946965):2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at abix.c(:com.google.android.gms@231312047@23.13.12 (190800-519946965):6)
        at abix.run(:com.google.android.gms@231312047@23.13.12 (190800-519946965):8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at abod.run(:com.google.android.gms@231312047@23.13.12 (190800-519946965):0)
        at java.lang.Thread.run(Thread.java:920)
2023-04-24 15:29:40.930 731-731/? E/ndroid.systemu: Failed to open APK '/data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk': I/O error
2023-04-24 15:29:40.932 731-731/? E/ndroid.systemu: Failed to open APK '/data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk': I/O error
2023-04-24 15:29:40.932 731-731/? E/ResourcesManager: failed to add asset path '/data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk'
    java.io.IOException: Failed to load asset path /data/app/~~7QXqZkOe6fjMrl9zdHtrKQ==/com.supper.athler1c-T_CpZOp2_cbfxt8wO44tDA==/base.apk
        at android.content.res.ApkAssets.nativeLoad(Native Method)
```

# SNaP
![1](https://user-images.githubusercontent.com/24685590/233957955-b5d8ad0d-c756-4fea-9148-72ba35deafea.PNG)

**Comment by sakibguy** [comment]
# Skipped
