### ISSUE TITLE
"CustomerProfileController" not found. You need to call "Get.put(CustomerProfileController())" or "Get.lazyPut(()=>CustomerProfileController())"

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#43]
```
======== Exception caught by widgets library =======================================================
The following message was thrown building Builder:
"CustomerProfileController" not found. You need to call "Get.put(CustomerProfileController())" or "Get.lazyPut(()=>CustomerProfileController())"

The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///D:/alicelabs/lastest/myalice_app/lib/main.dart:105:12
When the exception was thrown, this was the stack: 
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:305:7)
#1      Inst.find (package:get/get_instance/src/extension_instance.dart:69:45)
#2      new _OrderHistoryState (package:myalice/screens/customerProfile/orderHistory.dart:31:47)
#3      OrderHistory.createState (package:myalice/screens/customerProfile/orderHistory.dart:27:39)
#4      new StatefulElement (package:flutter/src/widgets/framework.dart:4891:25)
#5      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:758:38)
...     Normal element mounting (275 frames)
#280    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#281    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#282    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#283    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5883:32)
#284    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#285    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#286    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#287    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#289    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#291    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#292    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#293    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#294    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#296    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#297    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#298    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:108:11)
#299    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#300    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#301    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#302    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#303    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#304    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#305    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#306    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#307    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#308    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#309    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#310    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#311    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#312    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#313    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#314    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#315    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#316    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#317    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#318    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#319    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#320    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#321    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#322    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#323    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#327    _invoke (dart:ui/hooks.dart:151:10)
#328    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#329    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

## Snap
![1](https://user-images.githubusercontent.com/24685590/180179779-cb047283-6795-4537-a149-b04e71896e94.PNG)

**Comment by sakibguy** [comment]
## EFFORT 1
https://stackoverflow.com/questions/69104878/xxxcontroller-not-found-you-need-to-call-get-put-or-get-lazyput
