### ISSUE TITLE
SG-MYALICE: Null check operator used on a null value

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#47]
# Problem
> When clicked on imu1 imu2 list item then click event didn't work and terminal ended with an exception below

![1](https://user-images.githubusercontent.com/24685590/181195550-e156295d-8028-4f52-bbb6-1514ad683b87.png)

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _TicketsState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:myalice/screens/inboxScreen/customWidgets/tickets.dart:491:54)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#17     _invoke1 (dart:ui/hooks.dart:170:10)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#3465e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(161.2, 534.8)
  finalLocalPosition: Offset(145.2, 25.0)
  button: 1
  sent tap down
====================================================================================================
```

**Comment by sakibguy** [comment]
# Solution 
> Receive perfectly JSON key type to dart type. Did mistake on JSON int type to dart String type cast. Made int as JSON int then fixed. 

![1](https://user-images.githubusercontent.com/24685590/181266245-e3dd6c1c-530e-4621-bd8c-a118d66bbd33.png)
![2](https://user-images.githubusercontent.com/24685590/181266262-5dcc8cee-cbb1-47c8-87b3-1b8ea535f4da.png)

**Comment by sakibguy** [comment]
# Exception caught by widgets library
> Null check operator used on a null value

### The relevant error-causing widget was:

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building ConversationBaseWidget(dirty, state: _ConversationBaseWidget#cfc04):
Null check operator used on a null value

The relevant error-causing widget was: 
  ConversationBaseWidget ConversationBaseWidget:file:///D:/myalice_app/lib/screens/chatDetails/chatDetails.dart:367:43
When the exception was thrown, this was the stack: 
#0      _ConversationBaseWidget.getNameInitials (package:myalice/screens/chatDetails/customWidgets/conversationWidgets/conversationBaseWidget.dart:65:34)
#1      _ConversationBaseWidget.build (package:myalice/screens/chatDetails/customWidgets/conversationWidgets/conversationBaseWidget.dart:249:47)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (41 frames)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#54     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1405:37)
#55     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1390:20)
#56     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#57     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1382:12)
#58     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:353:23)
#59     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2246:59)
#60     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1035:15)
#61     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2246:14)
#62     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:342:5)
#63     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:428:5)
#64     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#66     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:149:12)
#67     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:386:11)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#69     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:516:13)
#70     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1960:12)
#71     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1905:20)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#88     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#94     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#96     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552:11)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#98     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#101    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#102    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#103    RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:903:45)
#104    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938:32)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#106    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#109    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#112    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#113    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#114    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1055:7)
#115    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#116    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#118    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#120    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#121    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#122    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#123    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1462:11)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#125    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#126    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#127    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
#128    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
#129    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
I/flutter ( 8965): Please wait f
#130    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#131    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#132    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1055:7)
#133    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#134    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#135    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1973:7)
#136    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:999:18)
#137    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:513:19)
#138    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#139    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#140    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#141    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#142    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#143    _invoke (dart:ui/hooks.dart:148:13)
#144    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#145    _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================
```

### SNaP
![Screenshot (438)](https://user-images.githubusercontent.com/24685590/202904640-ffa87e15-7923-4122-9cfe-066db3c529d0.png)

### Affected by UI
![Screenshot (439)](https://user-images.githubusercontent.com/24685590/202904722-9d3deb6a-958c-44b7-9839-757b81108a2e.png)

**Comment by sakibguy** [comment]
> Fixed
