### ISSUE TITLE
[ORG] SG-MYALICE: Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch!

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#65]
# Problem 1
```
Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch!
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:123)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1396)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3514)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3507)
```

```
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
	at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
	at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
	at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1629)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
```

`Exception: Gradle task assembleDevDebug failed with exit code 1`

**Comment by sakibguy** [comment]
# Solution 1
> Launched without err on laptop.

**Comment by sakibguy** [comment]
# CannonAngle
> https://github.com/Makeapp-Poland/ru_makeapp-rebuild-CannonAngle

## Prob 2
![1](https://github.com/sakibguy/worked-issues/assets/24685590/4435fc8c-c2ed-419c-a00a-6ef234d8245d)

**Comment by sakibguy** [comment]
# SoccerPair
https://github.com/Makeapp-Poland/ru_makeapp-rebuild-SoccerPair

# Prob
![1](https://github.com/sakibguy/worked-issues/assets/24685590/38d7d60d-5dff-4ce5-9c70-d77f5fb75b1f)

**Comment by sakibguy** [comment]
# Same issued default kt template project on Android studio
![1](https://github.com/sakibguy/worked-issues/assets/24685590/d0e16f0a-789c-4b31-8c13-75e6160ff49e)

# Efforts
1- https://stackoverflow.com/questions/42802270/tag-mismatch-error-android-studio
2- Failed https://stackoverflow.com/questions/29808199/error-running-android-gradle-project-sync-failed-please-fix-your-project-and-t
Updated plugins
https://developer.android.com/build/releases/gradle-plugin#updating-plugin

```
plugins {
    id("com.android.application") version "8.0.0" apply false
    id("com.android.library") version "8.0.0" apply false
    id("org.jetbrains.kotlin.android") version "1.5.31" apply false
}
```
