### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "ru.slybeaver.slycalendarview.SlyCalendarView" on path: DexPathList

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#70]
## Problem 
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "ru.slybeaver.slycalendarview.SlyCalendarView" on path: DexPathList[[dex file "/data/data/com.cupthrees1x.f1vee/code_cache/.overlay/base.apk/classes6.dex", zip file "/data/app/~~bFFSPO1R6EP3Vfrh3v4Inw==/com.cupthrees1x.f1vee-7ufYajibEMJf-s6H30rETA==/base.apk"],nativeLibraryDirectories=[/data/app/~~bFFSPO1R6EP3Vfrh3v4Inw==/com.cupthrees1x.f1vee-7ufYajibEMJf-s6H30rETA==/lib/x86_64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

## Snap
![1](https://user-images.githubusercontent.com/24685590/188073930-4282f0a5-4e57-4c6d-9b9b-d5ca18344050.PNG)

**Comment by sakibguy** [comment]
## Solution 
> Remove injected bin 
![1](https://user-images.githubusercontent.com/24685590/188074721-5205b044-2edb-4f64-9b37-671de4ad71a2.PNG)
