### ISSUE TITLE
java.lang.SecurityException: No permission to access APN settings

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#71]
# Problem 

```
java.lang.SecurityException: No permission to access APN settings
        at com.android.providers.telephony.TelephonyProvider.checkPermission(TelephonyProvider.java:4788)
        at com.android.providers.telephony.TelephonyProvider.checkPermissionCompat(TelephonyProvider.java:4805)
        at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:3678)
        at android.content.ContentProvider.query(ContentProvider.java:1408)
        at android.content.ContentProvider.query(ContentProvider.java:1504)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:272)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
        at android.os.Binder.execTransactInternal(Binder.java:1179)
        at android.os.Binder.execTransact(Binder.java:1143)
```

## Snap 
![1](https://user-images.githubusercontent.com/24685590/188259999-7fce0c83-495d-452d-8e24-971587f57256.PNG)

**Comment by sakibguy** [comment]
# Solution
> Been missing to initialize ArrayList<>.

`ArrayList<UpcomingWord> upcomingWords = new ArrayList<UpcomingWord>();`
