### ISSUE TITLE
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>?'

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#77]
# PROB

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>?'
E/flutter (22729): #0      new ChatDataSource.fromJson (package:myalice/models/responseModels/chatResponse.dart:122:10)
E/flutter (22729): #1      new ChatResponse.fromJson.<anonymous closure> (package:myalice/models/responseModels/chatResponse.dart:18:29)
E/flutter (22729): #2      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (22729): #3      new ChatResponse.fromJson (package:myalice/models/responseModels/chatResponse.dart:17:40)
E/flutter (22729): #4      ChatApiController.getChats.<anonymous closure> (package:myalice/controllers/apiControllers/chatApiController.dart:303:34)
E/flutter (22729): #5      ChatApiController.getChats.<anonymous closure> (package:myalice/controllers/apiControllers/chatApiController.dart:299:15)
E/flutter (22729): #6      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (22729): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (22729): <asynchronous suspension>
```

# SNaP
![Screenshot (225)](https://user-images.githubusercontent.com/24685590/192568886-a86fb07c-fc9f-4486-a8f4-72aafedbf7f3.png)
![Screenshot (226)](https://user-images.githubusercontent.com/24685590/192568898-c49cac91-ab1d-427d-8811-76655cf67fe6.png)
![Screenshot (227)](https://user-images.githubusercontent.com/24685590/192568911-52dfda6a-514a-4a2e-b819-8827dac31cae.png)

**Comment by sakibguy** [comment]
# SOL

> Commented incompatible types.

![Screenshot (228)](https://user-images.githubusercontent.com/24685590/192570050-1de37ccc-36f8-4507-afde-37d2d56a5fe3.png)
