### ISSUE TITLE
SG-MYALICE: Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#79]
# PROB
 ```
Playback error
E/ExoPlayerImplInternal( 8505):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
E/ExoPlayerImplInternal( 8505):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 8505):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal( 8505):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal( 8505):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 8505):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
E/ExoPlayerImplInternal( 8505):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412
```

## SNaP
![Screenshot (241)](https://user-images.githubusercontent.com/24685590/193439875-4c189140-c211-4443-8756-a08dfe5cf2be.png)

**Comment by sakibguy** [comment]
# SOLn
> Nargis Apu fixed.
