### ISSUE TITLE
CastError was thrown building ConversationBaseWidget

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#80]
# PROB
```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building ConversationBaseWidget(dirty, dependencies: [MediaQuery], state: _ConversationBaseWidget#413eb):
Null check operator used on a null value

The relevant error-causing widget was: 
  ConversationBaseWidget ConversationBaseWidget:file:///D:/myalice_app/lib/screens/chatDetails/chatDetails.dart:400:47
When the exception was thrown, this was the stack: 
#0      _ConversationBaseWidget.build (package:myalice/screens/chatDetails/customWidgets/conversationWidgets/conversationBaseWidget.dart:373:69)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
```

## SNaP
![Screenshot (242)](https://user-images.githubusercontent.com/24685590/193440092-19e0bd66-436c-4f7f-89cb-2afcf1c3a8b5.png)

**Comment by sakibguy** [comment]
# SOL 1

STEP 1: Commented 

```
/*ConvBtnQuickReplyWidget(
                                                        buttons: widget
                                                            .conversation
                                                            .data!
                                                            .buttons!,
                                                        type: widget
                                                            .conversation.type!,
                                                        text: widget
                                                                .conversation
                                                                .data!
                                                                .text ??
                                                            "")*/
```

STEP 2: Inject new snippet

```
ConvBtnQuickReplyWidget(
                                                        buttons: [],
                                                        type: widget
                                                            .conversation.type!,
                                                          text: widget
                                                              .conversation
                                                              .data!
                                                              .text ??
                                                              ""
                                                      )
```

**Comment by sakibguy** [comment]
# RESULTS 
> Gallery, buttons, files, audios, texts, ...etc all.

![Screenshot (243)](https://user-images.githubusercontent.com/24685590/193441931-eb6232a4-f756-4748-9cf8-54518cba8fee.png)
![Screenshot (244)](https://user-images.githubusercontent.com/24685590/193441934-b3952053-d0e9-42f6-a610-ad15a1d7335f.png)
![Screenshot (245)](https://user-images.githubusercontent.com/24685590/193441936-75ec95c4-2abd-4396-8bd9-ce115ba2d19b.png)
![Screenshot (246)](https://user-images.githubusercontent.com/24685590/193441937-be135a29-1a19-4274-aa3f-ad807e61e61d.png)
![Screenshot (247)](https://user-images.githubusercontent.com/24685590/193441940-a000b466-82d0-43bc-b94a-7167cd0db18e.png)
