### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory"

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#9]
## Problem 

```
java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/com.sct.nextdoor--Zc40Gac-EY8OdZr5Kd-yQ==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
        at android.app.LoadedApk.updateApplicationInfo(LoadedApk.java:370)
        at android.app.ActivityThread.handleDispatchPackageBroadcast(ActivityThread.java:5951)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1941)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at com.android.server.SystemServer.run(SystemServer.java:541)
        at com.android.server.SystemServer.main(SystemServer.java:349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
2022-04-25 22:43:16.513 2354-2958/com.google.android.apps.nexuslauncher E/ActivityThread: Failed to find provider info for com.google.android.apps.wellbeing.api
2022-04-25 22:43:16.632 1798-1821/? E/installd: Failed to delete /data/app/vmdl82167913.tmp: No such file or directory
```

![1](https://user-images.githubusercontent.com/24685590/165138218-a680d74c-618a-4af8-99b1-05f7253e8e70.PNG)

**Comment by sakibguy** [comment]
## Fixed 

> Step 1: Build -> Clean Project 

> Step 2: File -> Invalidate caches / Restart

> Step 3: Update android:name=".MainActivity" to android:name="com.sct.nextx.MainActivity"


![1](https://user-images.githubusercontent.com/24685590/165140543-43e487be-41b9-40bd-bbc1-3cedba9bf795.PNG)
![2](https://user-images.githubusercontent.com/24685590/165140547-974fc455-70ac-441a-9152-2880cd6cf3db.PNG)
