### ISSUE TITLE
SG-MYALICE: DioError [DioErrorType.response]: Http status error [426]

### ISSUE THREAD

**Issue by sakibguy** [sakibguy/worked-issues#90]
# PROB

```
DioError [DioErrorType.response]: Http status error [426]
I/flutter (20277): Source stack:
I/flutter (20277): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (20277): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (20277): #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
I/flutter (20277): #3      DioController.fetchNewsArticle (package:practice_syntax_from_0/app/dio/DioController.dart:52:40)
I/flutter (20277): #4      _HomePageState.build (package:practice_syntax_from_0/main.dart:205:47)
I/flutter (20277): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
I/flutter (20277): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
I/flutter (20277): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
I/flutter (20277): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
I/flutter (20277): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
I/flutter (20277): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
I/flutter (20277): #11     ComponentElement.mount (package:flutter/src/widge
```

# SNaP
![Screenshot (370)](https://user-images.githubusercontent.com/24685590/198220773-511f4b1c-510b-4bb8-afd7-0f99568a2e5e.png)

**Comment by sakibguy** [comment]
# Received data

```
I/flutter (21969): [---ok---] nr {"status":"ok","totalResults":14848,"articles":[{"source":{"id":"rt","name":"RT"},"author":"RT en Español\n , RT en Español","title":"WSJ: Bancos empezaron a transferir el dinero a Musk para sellar el acuerdo de compra de Twitter","description":"Este viernes 28 de octubre es la fecha límite que impuso un tribunal estadounidense para ultimar la adquisición.","url":"https://actualidad.rt.com/actualidad/446127-bancos-traslado-dinero-musk-acuerdo-twitter","urlToImage":"https://mf.b37mrtl.ru/actualidad/public_images/2022.10/article/635a3f8d59bf5b46e3753ad1.jpg","publishedAt":"2022-10-27T08:37:00Z","content":"Diversos bancos ya han empezado a transferir 13.000 millones de dólares al director general de Tesla y SpaceX, Elon Musk, para que el multimillonario pueda sellar su acuerdo de compra de Twitter, inf… [+2355 chars]"},{"source":{"id":null,"name":"Quartz India"},"author":"Ananya Bhattacharya","title":"Ford and Volkswagen hit reverse gear on self-driving cars - Quartz","description":"Legacy 
D/EGL_emulation(21969): app_time_stats: avg=32.17ms min=6.63ms max=120.07ms count=29
D/EGL_emulation(21969): app_time_stats: avg=36.39ms min=10.53ms max=68.44ms count=26
D/EGL_emulation(21969): app_time_stats: avg=29.58ms min=7.96ms max=59.55ms count=30
I/flutter (21969): [---ok---] nr {"status":"ok","totalResults":14848,"articles":[{"source":{"id":"rt","name":"RT"},"author":"RT en Español\n , RT en Español","title":"WSJ: Bancos empezaron a transferir el dinero a Musk para sellar el acuerdo de compra de Twitter","description":"Este viernes 28 de octubre es la fecha límite que impuso un tribunal estadounidense para ultimar la adquisición.","url":"https://actualidad.rt.com/actualidad/446127-bancos-traslado-dinero-musk-acuerdo-twitter","urlToImage":"https://mf.b37mrtl.ru/actualidad/public_images/2022.10/article/635a3f8d59bf5b46e3753ad1.jpg","publishedAt":"2022-10-27T08:37:00Z","content":"Diversos bancos ya han empezado a transferir 13.000 millones de dólares al director general de Tesla y SpaceX, Elon Musk, para que el multimillonario pueda sellar su acuerdo de compra de Twitter, inf… [+2355 chars]"},{"source":{"id":null,"name":"Quartz India"},"author":"Ananya Bhattacharya","title":"Ford and Volkswagen hit reverse gear on self-driving cars - Quartz","description":"Legacy 
```

# SNaP
![Screenshot (372)](https://user-images.githubusercontent.com/24685590/198238978-7ff40aef-b070-4c24-948f-a0dd000821e7.png)

**Comment by sakibguy** [comment]
# Solved 
>  Issued as newsapi.org site's api updated (endpoint & token). Debugged response & UI data -> Fixed.

# SNaP 
![Screenshot (373)](https://user-images.githubusercontent.com/24685590/198243944-8df16411-20c5-4f14-8f32-6d3ae08bac7f.png)

**Comment by sakibguy** [comment]
https://github.com/sakibguy/mobileapps-flutter/pull/27

**Comment by sakibguy** [comment]
# Received data by API call but UI side getting null data

![1](https://user-images.githubusercontent.com/24685590/198293001-2a4eef7f-8eba-4f0f-8284-4ff09d8ba405.png)

**Comment by sakibguy** [comment]
# DioError [DioErrorType.response]: Http status error [401]

> Log showing above err.

![Screenshot_20221027_190734](https://user-images.githubusercontent.com/24685590/198951296-ee514d0a-4e73-4393-9961-7004d79cf280.png)

**Comment by sakibguy** [comment]
# Addressed 
> Blue marked line not executing. Model parsing failed. 

![Screenshot_20221031_150355](https://user-images.githubusercontent.com/24685590/198971483-3e110d9e-d870-47ca-bb5d-517570d609e4.png)

**Comment by sakibguy** [comment]
# rethrow
https://stackoverflow.com/questions/68119285/the-body-might-complete-normally-causing-null-to-be-returned-but-the-return

**Comment by sakibguy** [comment]
> As solved once so moving to close.
